In [2]:
# Dependencies and Setup
import pandas as pd
import numpy as np

Coffee_data = "Coffee_commodity_USDA.csv"

# Read Data File and store into Pandas Data Frames
Coffee_data_df = pd.read_csv(Coffee_data)
Coffee_data_df.head()

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value
0,711100,"Coffee, Green",AG,Algeria,2003,2012,6,29,Arabica Production,2,(1000 60 KG BAGS),0
1,711100,"Coffee, Green",AG,Algeria,2004,2012,6,29,Arabica Production,2,(1000 60 KG BAGS),0
2,711100,"Coffee, Green",AG,Algeria,2005,2012,6,29,Arabica Production,2,(1000 60 KG BAGS),0
3,711100,"Coffee, Green",AG,Algeria,2006,2012,6,29,Arabica Production,2,(1000 60 KG BAGS),0
4,711100,"Coffee, Green",AG,Algeria,2007,2012,6,29,Arabica Production,2,(1000 60 KG BAGS),0